version: '3.3'

services:
  db:
    container_name: "${DB_CONTAINER_NAME:-tg_bot_database-image}"
    image: sameersbn/postgresql:12-20200524
    env_file:
      - ".env"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - botnet
    volumes:
      - ./postgres_data:/var/lib/postgresql

  redis:
    image: redis:6.0-alpine
    container_name: "${REDIS_CONTAINER_NAME:-tg_bot_redis-image}"
    hostname: redis
    env_file:
      - ".env"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_config:/usr/local/etc/redis
      - ./redis_data:/data
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - botnet

  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    restart: always
    env_file:
      - ".env"
    networks:
      - botnet
    depends_on:
      - db
      - redis

networks:
  botnet:
    driver: bridge